apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
spec:
  selector:
    app: devops-project
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer